In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [7]:
np.array([(2**a)/a for a in np.arange(1, 20)], dtype=np.double)

array([  2.00000000e+00,   2.00000000e+00,   2.66666667e+00,
         4.00000000e+00,   6.40000000e+00,   1.06666667e+01,
         1.82857143e+01,   3.20000000e+01,   5.68888889e+01,
         1.02400000e+02,   1.86181818e+02,   3.41333333e+02,
         6.30153846e+02,   1.17028571e+03,   2.18453333e+03,
         4.09600000e+03,   7.71011765e+03,   1.45635556e+04,
         2.75941053e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [9]:
np.sum(np.array([0.1**(3*i)*0.2**(4*i) for i in np.arange(0, 5)], dtype=np.double))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [44]:
mat = np.zeros((8, 8))
mat[1:8:2, 0:8:2] = 1
mat[0:8:2, 1:8:2] = 1
mat

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [79]:
X = np.random.random((5, 2))

def toPolar(xy): 
    return np.sqrt(xy[0]**2 + xy[1]**2), np.arctan2(xy[1], xy[0])

np.array([toPolar(x) for x in X])

array([[ 0.63279888,  0.9470823 ],
       [ 0.99242781,  1.39471297],
       [ 0.94304844,  0.5843474 ],
       [ 1.08654824,  0.75478115],
       [ 0.75380765,  1.26368211]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [285]:
X = np.random.random((10, 10))

x_id = np.argmax(X)
x_one_dim = X.reshape(100, 1)
ind = np.where(X == x_one_dim[x_id])
x_id_max, y_id_max = ind[0][0], ind[1][0]
print(x_id_max, y_id_max)
print('max element = {m}'.format(m = X[x_id_max, y_id_max]))
print(X < X[x_id_max, y_id_max])

5 5
max element = 0.9988754107148419
[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True False  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [131]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
dists = np.array([np.linalg.norm(X[i] - y) for i in range(0, X.shape[0])])
id_min = np.argmin(dists)
print(X[id_min])

[ 0.45446157  0.71515282]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [200]:
def weird_func(x):
    fst = lambda y: y**2 + 2*y + 6
    scd = lambda y: y + 6
    trd = lambda y: y**2 + 4*y - 4
    if type(x) is np.ndarray or type(x) is np.array or type(x) is list:
        f = fst(x[x<=0])
        s = scd(x[(2>x) & (x>0)])
        t = trd(x[x>=2])
        return np.array([fi for fi in f] + [si for si in s] + [ti for ti in t])  
    else:
        if x <= 0: return fst(x)
        elif (2 > x) & (0 > x): return scd(x)
        else: return trd(x)
print(weird_func(np.linspace(-3, 3)))
print(weird_func(2))

[  9.           8.52519783   8.08038317   7.66555602   7.28071637
   6.92586422   6.60099958   6.30612245   6.04123282   5.8063307
   5.60141608   5.42648896   5.28154935   5.16659725   5.08163265
   5.02665556   5.00166597   5.00666389   5.04164931   5.10662224
   5.20158267   5.32653061   5.48146606   5.666389     5.88129946
   6.06122449   6.18367347   6.30612245   6.42857143   6.55102041
   6.67346939   6.79591837   6.91836735   7.04081633   7.16326531
   7.28571429   7.40816327   7.53061224   7.65306122   7.7755102
   7.89795918   8.1636818    9.16326531  10.19283632  11.25239484
  12.34194086  13.46147439  14.61099542  15.79050396  17.        ]
8


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [232]:
X = np.random.random((10, 10))

X_m = np.array([X[i] - np.mean(X[i]) for i in range(0, len(X))], dtype=np.double)
print([np.mean(X_m[i]) for i in range(0, len(X_m))])

[3.3306690738754695e-17, -3.3306690738754695e-17, 1.1102230246251566e-17, -1.1102230246251566e-17, -1.1102230246251566e-17, -1.3322676295501878e-16, -2.2204460492503132e-17, 1.1102230246251566e-17, 4.4408920985006264e-17, 3.3306690738754695e-17]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [249]:
X = np.random.normal(loc=5, scale=2., size=1000)
e = np.mean(X)
d = (1/X.shape[0])*(sum((X - e)**2))
print(e)
print(d)

5.0345890375
4.11100906599


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [3]:
def build_mat(dim):
    mat = np.arange(0, dim)
    for i in range(1, dim):
        tmp = np.hstack((np.arange(i, dim), np.arange(0, i)))
        mat = np.vstack((mat, tmp))
    return mat

print(build_mat(5))
            

[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]
